apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-ui
  namespace: cloud-native-ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce-ui
  template:
    metadata:
      labels:
        app: ecommerce-ui
    spec:
      containers:
        - name: ecommerce-ui
          image: olymahmudmugdho/cne-ecommerce-ui:1bd8c78e40dbd4414d2ee29f14423e159a81cda6
          ports:
            - containerPort: 4173
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
