apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: cloud-native-ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: olymahmudmugdho/order-service:1f070afb049ece9a8a3224f72018c3de72eb83ab
          ports:
            - containerPort: 8082
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
